---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4
    driver_config:
        box: centos6.4-chef
suites:
  - name: default
    run_list:
      - recipe[cpanm_test::default]
      - recipe[minitest-handler]
    attributes:
      cpanm:
        install_from: file
  - name: source
    run_list:
      - recipe[cpanm_test::source]
      - recipe[minitest-handler]
    attributes:
